### PR TITLE
FACES-2843 Refactor HeadResponseWriterLiferayImpl to use JspFactory.getPageContext() instead of PageContextStringImpl

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by juangon** [comment]
:+1:  thanks Kyle. Had this on my task queue.

**Comment by stiemannkj1** [comment]
Thanks @juangon, I just did bridge-ext, but [FACES-2844](https://issues.liferay.com/browse/FACES-2844) is a similar task assigned to you for Liferay Faces Portal.

**Comment by ngriffin7a** [comment]
Merged and backported to 6.x, 5.x, and 4.x. Thank you.

**Comment by stiemannkj1** [comment]
@ngriffin7a, I believe that this should be backported all the way to `2.x` unless I'm missing something.

**Comment by stiemannkj1** [comment]
@ngriffin7a nevermind, I sent the backport (https://github.com/liferay/liferay-faces-bridge-ext/pull/85) and forgot about it. Haha! Oops!

**Pull request merged**
