### PR TITLE
FACES-2629 Forms cause Single Page Application (SennaJS) form submission in Liferay 7

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
Merged into master (5.x) and backported to 4.x. Thank you.

**Comment by ngriffin7a** [comment]
@stiemannkj1: Please send a follow-up PR with the following changes:
1) Rename SennaJSDisablingRendererImpl to SennaJSDisablingRenderer
2) Move RenderKitLiferayImpl.DISABLE_SENNAJS_ELEMENT_NAMES to SennaJSDisablingResponseWriterImpl (the only place it is used)
3) Make DISABLE_SENNAJS_ELEMENT_NAMES be a Set<String> and have it be an instance of java.util.HashSet for performance. Actually a simple ("a".equals(name) || "form".equals(name)) might be even faster and simpler.

**Comment by stiemannkj1** [comment]
@ngriffin7a, the reason that I put `DISABLE_SENNAJS_ELEMENT_NAMES` in `RenderKitLiferayImpl` was to make it so that devs only need to change one file to disable SennaJS for a component. If you'd rather have it in the `ResponseWriter`, then I agree, it should just be a simple `("a".equals(name) || "form".equals(name))` instead.

What do you think?

**Comment by stiemannkj1** [comment]
Done in #24.

**Pull request merged**
