### PR TITLE
FACES-1387 Develop primefaces push portlet demos (add jar for atmosphere support in Liferay 7)

### PR DESCRIPTION
**Pull request by stiemannkj1**
@ngriffin7a, this PR must be merged after #115. Also, when backporting, make sure to change the version to match the version in **`bridge-ext/pom.xml`** (or at least the major version). Thanks.

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@ngriffin7a, or I can backport if you would like. Also, we only need to backport this all the way to `5.x`.

**Comment by ngriffin7a** [comment]
Merged and backported to 4.x. Also fixed `<version>` in pom.xml backports. Note that 5.x is "5.0.0-SNAPSHOT" and 4.x is "4.0.0-SNAPSHOT" since they have never been released before. Thank you.

**Comment by stiemannkj1** [comment]
@ngriffin7a, this won't build in `4.x` please revert.

**Comment by ngriffin7a** [comment]
@stiemannkj1 Compiling fine in 4.x.

**Pull request merged**
